version: "3.8"

services:
  nextjs:
    build: .
    container_name: navalia-shoppingcart-fe
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/shoppingcart
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    container_name: navalia-shoppingcart-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shoppingcart
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
