version: "3.8"

services:
  db:
    image: postgres:16-alpine
    container_name: navalia-shoppingcart-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shoppingcart
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shoppingcart-app
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/shoppingcart
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  db_data:
