import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import theme from "@/theme";
import { ThemeProvider, StyledEngineProvider } from "@mui/material/styles";
import "./globals.css";

import Header from "./components/header/Header";
import Footer from "./components/footer/Footer";
import { AppProviders } from "./contexts/AppProviders";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <StyledEngineProvider injectFirst>
          <ThemeProvider theme={theme}>
            <AppRouterCacheProvider>
              <Header />
              <AppProviders> {children}</AppProviders>
              <Footer />
            </AppRouterCacheProvider>
          </ThemeProvider>
        </StyledEngineProvider>
      </body>
    </html>
  );
}
